/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitrial;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.LinkedList;

/**
 *
 * @author user
 */
public class priorityGUI extends javax.swing.JDialog {

    /**
     * Creates new form priorityGUI
     */
    public priorityGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        processNametxt3 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        arrivaltxt3 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        btimetxt3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        prioritytxt = new javax.swing.JTextPane();
        simbtn3 = new javax.swing.JButton();
        resetbtn3 = new javax.swing.JButton();
        nonpreemrad = new javax.swing.JRadioButton();
        preemprad = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        avtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("priority schedular");
        setBackground(new java.awt.Color(253, 230, 243));

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("process sequence");

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("arrival time");

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("burst time");

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("priority number");

        jScrollPane1.setViewportView(processNametxt3);

        jScrollPane2.setViewportView(arrivaltxt3);

        jScrollPane3.setViewportView(btimetxt3);

        jScrollPane4.setViewportView(prioritytxt);

        simbtn3.setText("Simulate");
        simbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simbtn3ActionPerformed(evt);
            }
        });

        resetbtn3.setText("Reset");
        resetbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtn3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(nonpreemrad);
        nonpreemrad.setText("non preemtive");
        nonpreemrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonpreemradActionPerformed(evt);
            }
        });

        buttonGroup1.add(preemprad);
        preemprad.setText("preemptive");

        jLabel7.setText("eg.");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("=1");

        jLabel8.setText("=4");

        jLabel9.setText("=2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setText("eg.");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("=p1");

        jLabel12.setText("=p2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel14.setText("average time is");

        avtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(simbtn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetbtn3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(nonpreemrad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preemprad)
                            .addComponent(avtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nonpreemrad)
                    .addComponent(preemprad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbtn3)
                    .addComponent(simbtn3))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simbtn3ActionPerformed
        String pns=processNametxt3.getText();//process name string
        pns=pns.replaceAll("[\n\r]", "");
        String ats=arrivaltxt3.getText();//processes arrival time strings
        ats=ats.replaceAll("[\n\r]", "");
        String bts=btimetxt3.getText();//processes burst time string
        bts=bts.replaceAll("[\n\r]", "");
        String prioritystring=prioritytxt.getText();//processes burst time string
        prioritystring=prioritystring.replaceAll("[\n\r]", "");
        
        LinkedList pnl=new LinkedList();//process name list
        LinkedList btl=new LinkedList();//burst time list
        LinkedList atl=new LinkedList();//arrival time list
        LinkedList prioritylist=new LinkedList();//priority time list 
        
        FcfsGUI obj=new FcfsGUI();//creating object of class FcfsGUI to call funtions in its class
        
        obj.parseStringToStringList(pns,pnl);//parse process name string (pns)into substrings and put them in linked list(pnl)
        obj.parseStringToIntList(bts,btl);//parse burst time string(bts) into integers and put them in linked list (btl)
        obj.parseStringToIntList(ats,atl);//parse arrival time string(ats) into integer and put them in linked list(atl) 
        obj.parseStringToIntList(prioritystring,prioritylist);
        
        int [] stl=new int[pnl.size()];
                
        if(nonpreemrad.isSelected())
        {
            LinkedList currentp=new LinkedList();
            LinkedList currentb=new LinkedList();
            LinkedList currentprio=new LinkedList();
            LinkedList finishedp=new LinkedList();
            
            SortAccordingToArrival(atl,btl,pnl,prioritylist);
        
            int start=(int)atl.get(0); int end=0;
            System.out.print(start);
        
            while(pnl.size()!=finishedp.size())
            {
                int t=start;
                for(int i=0;i<pnl.size();i++)//check for the current processes
                {
                    if((int)atl.get(i)<=t && !(finishedp.contains(pnl.get(i))))
                    {
                        currentp.add(pnl.get(i));
                        currentb.add(btl.get(i));
                        currentprio.add(prioritylist.get(i)); 
                    }
                }
                if(!currentp.isEmpty())
                {
                    SortAccordingToPriority(currentb,currentp,currentprio);
                    end=start+(int)currentb.get(0);
                    System.out.print("|"+currentp.get(0));
                    for(int k=0;k<(int)currentb.get(0);k++)
                        System.out.print(" ");
                    System.out.print(end);
                    int index=pnl.indexOf(currentp.get(0));//get index of finished processs name from pnl 
                    stl[index]=start;
                    finishedp.add(pnl.get(index));
                    currentp.clear(); 
                    currentb.clear();
                    start=end;
                }
                else
                {
                    start++;
                    System.out.print("| "+start);    
                }
            }
            System.out.println();
            double avg=CalcAvgWait(atl,stl);
            String avgs=Double.toString(avg);
            avtxt.setText(avgs);
        }

    }//GEN-LAST:event_simbtn3ActionPerformed
    private void SortAccordingToArrival(LinkedList atl,LinkedList btl,LinkedList pnl,LinkedList priolist)
    {
        boolean flag = true;   
        Object temp,temp2,temp3,temp4;  //holding variable
        while ( flag )
        {
           flag= false;    //set flag to false awaiting a possible swap
           for(int j=0; j<atl.size()-1; j++ )
           {
               if ( (int)atl.get(j) > (int)atl.get(j+1) )   
               {
                   //swap arrival time
                   temp4=atl.get(j);
                   atl.set(j,atl.get(j+1));
                   atl.set(j+1, temp4);
                   //swap burst time
                   temp = btl.get(j);                
                   btl.set(j, btl.get(j+1));
                   btl.set(j+1, temp); 
                   //swap process name
                   temp2=pnl.get(j);
                   pnl.set(j, pnl.get(j+1));
                   pnl.set(j+1, temp2);
                   //swap priority
                   temp3=priolist.get(j);
                   priolist.set(j, priolist.get(j+1));
                   priolist.set(j+1, temp3);
                   flag = true;  
               } 
            } 
        } 
    }
    
    public void SortAccordingToPriority(LinkedList btl,LinkedList pnl,LinkedList prio)
    {
        if(btl.size()==1 || btl.size()==0)
            return;
        boolean flag = true;   
        Object temp,temp2,temp3;
        while ( flag )
        {
           flag= false;    //set flag to false awaiting a possible swap
           for(int j=0; j<prio.size()-1; j++ )
           {
               if ( (int)prio.get(j) > (int)prio.get(j+1))   
               {   
                   //swap burst time
                   temp = btl.get(j);                
                   btl.set(j, btl.get(j+1));
                   btl.set(j+1, temp); 
                   //swap process name
                   temp2=pnl.get(j);
                   pnl.set(j, pnl.get(j+1));
                   pnl.set(j+1, temp2);
                   flag = true;  
                   //swap prio
                   temp3 = prio.get(j);                
                   prio.set(j, prio.get(j+1));
                   prio.set(j+1, temp3); 
               } 
            } 
        } 
    } 

    /**
     *
     * @param al
     * @param sl
     * @return
     */
    public float CalcAvgWait(LinkedList al,int [] sl)
    {
        float sum=0.0f;
        for(int i=0;i<sl.length;i++)
            sum+=(sl[i]-(int)al.get(i)); // calculating sum of waiting time of all processes
        return sum/sl.length;
    }
    private void nonpreemradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonpreemradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonpreemradActionPerformed

    private void resetbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtn3ActionPerformed
        buttonGroup1.clearSelection();
        prioritytxt.setText("");
        processNametxt3.setText("");
        arrivaltxt3.setText("");  
        btimetxt3.setText("");// TODO add your handling code here:
        prioritytxt.setText("");
                avtxt.setText("");

    }//GEN-LAST:event_resetbtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(priorityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(priorityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(priorityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(priorityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new priorityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane arrivaltxt3;
    private javax.swing.JLabel avtxt;
    private javax.swing.JTextPane btimetxt3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton nonpreemrad;
    private javax.swing.JRadioButton preemprad;
    private javax.swing.JTextPane prioritytxt;
    private javax.swing.JTextPane processNametxt3;
    private javax.swing.JButton resetbtn3;
    private javax.swing.JButton simbtn3;
    // End of variables declaration//GEN-END:variables
}
